services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # inutile si Dockerfile s'appelle bien Dockerfile ici 
    ports:
      - "8501:8501"
    volumes:
      - ./data.bd:/app/data.bd
      - ./users.bd:/app/users.bd
    restart: unless-stopped # redémarre le conteneur sauf si on l'arrête manuellement
